### ISSUE TITLE
강좌 세팅 페이지 구현

### ISSUE THREAD

**Issue by Sally-SH** [2021-fall-cs492c-team-10/monorepo#100]
![image](https://user-images.githubusercontent.com/64458625/142372757-dfa8ff68-befe-4b44-8e29-c9f2c91400fb.png)

- [x] 강좌 세팅페이지 구현 #122 
- [x] 서버와 동기화 #187

**Comment by Sally-SH** [comment]
클래스 이름을 바꾸는 기능을 넣으려면 이름을 바꾸고 서버로 바뀐 내용을 전달할 버튼이 필요하지 않을까요?

**Comment by julielee16** [comment]
> 클래스 이름/비밀번호를 바꾸는 기능을 넣으려면 이름을 바꾸고 서버로 바뀐 내용을 전달할 버튼이 필요하지 않을까요? 아니면 세팅 페이지가 닫힐 때 자동으로 바뀐 내용을 전달하는 것으로 할까요?

저는 닫힐 때 자동으로 바뀐 내용을 전달하는 방식이 좋다 생각합니다!

**Comment by kimkanu** [comment]
아마 비슷한 내용을 계정 설정 페이지의 버튼을 넣느냐 마느냐로 이야기한 적이 있었는데, 버튼 없이 동기화하는 쪽이 더 나을 것 같다는 얘기가 나왔습니다!
