### ISSUE TITLE
클래스 페이지 내 유튜브 영상 set video 에러

### ISSUE THREAD

**Issue by Sally-SH** [2021-fall-cs492c-team-10/monorepo#204]
- [ ] 클래스 페이지에서 방장이 set video를 눌렀을 때 학생 페이지에는 영상이 세팅되는데, 방장 페이지에는 세팅되지 않는 문제를 발견
- [ ]  방장이 영상을 재생한 상태로 새로운 학생이 수업에 참여했을 때 학생 비디오가 재생되지 않는 문제가 가끔씩 발생

**Comment by kimkanu** [comment]
확인해 보겠습니다!
