### ISSUE TITLE
로그아웃 된 상태의 메인 페이지 디자인

### ISSUE THREAD

**Issue by kimkanu** [2021-fall-cs492c-team-10/monorepo#40]

**Comment by kimkanu** [comment]
제가 생각하고 있는 디자인은

![image](https://user-images.githubusercontent.com/22598138/144169582-2d331172-c133-42f3-978d-1d45e0121d54.png)

![image](https://user-images.githubusercontent.com/22598138/144169762-8eca04a4-ea09-48a6-af01-afc5cceb14b4.png)

**Comment by Sally-SH** [comment]
저는 원기둥 보다는 분산된 디자인이 좋은데, 이게 도형을 배치하기가 어렵지 않을까 걱정되네요
자칫하면 밋밋해 보이거나 너무 복잡해 보일 수도 있을 것 같아서요
하지만 잘 배치한다면 정말 예쁠 것 같습니다!

**Comment by kimkanu** [comment]
딱 저 예시 정도로 좌표 계산해서 three.js로 띄우면 될 것 같아요 
아마 들어갈 오브젝트가 저거랑 간단한 도형(저거 말고는 2D여도 될 거 같네요)만 있어도 로고랑 다른 문구 가운데에 들어가면 밋밋하지는 않을 것 같아요

**Comment by kimkanu** [comment]
처음 로드 시에 약간 터지면서 배치되는 듯한 애니메이션 넣으면 밋밋하지는 않을 것 같네요!

**Comment by julielee16** [comment]
이 부분을 너무나 늦게 봤네요. 만약 계속 진행하고 있으시다면 저도 정말 마음에 드는 디자인입니다! 말씀하신대로 좌표 계산해서 너무 UX에 거슬리지 않게 하면 정말 재미있을것 같아요!
