### ISSUE TITLE
Primary color와 destructive action color 구분 이슈

### ISSUE THREAD

**Issue by kimkanu** [2021-fall-cs492c-team-10/monorepo#47]

**Comment by kimkanu** [comment]
#47

* Primary color와 빨간색이 구분이 잘 안 간다는 피드백에 따라 빨간색의 hue를 살짝 올려봤습니다.

![Group 17(1)](https://user-images.githubusercontent.com/22598138/140633967-a9db901a-d619-4ff4-ab61-0a3736d48439.png)

**Comment by kimkanu** [comment]
바뀐 색상의 color blindness 테스트입니다. (가운데와 왼쪽 아래는 전색맹)

![Group 20](https://user-images.githubusercontent.com/22598138/140634095-b3837d7f-b872-44dc-b437-89adb5094b16.png)

**Comment by kimkanu** [comment]
보라색은 적색맹/약의 경우에 positive한 의미랑 겹치지만 보통 primary 액션이랑 positive한 액션은 의미에 차이가 크지 않으므로 겹쳐도 괜찮을 것 같기는 합니다.

![Group 20(1)](https://user-images.githubusercontent.com/22598138/140634264-91d60061-0cf5-4e7f-a88e-77648a0ad4c3.png)

**Comment by kimkanu** [comment]
초록색을 사용하는 경우도 있는데 초록색은 적록 색맹/약의 경우에(희소하지만) 색이 겹쳐서 의미 혼란이 클 거 같아요

![Group 20(2)](https://user-images.githubusercontent.com/22598138/140634464-577742c6-fbc1-404a-8810-255069f13153.png)

**Comment by Sally-SH** [comment]
![image](https://user-images.githubusercontent.com/64458625/140655570-0fa9fef3-981a-4527-9f33-d896daad0922.png)

세 번째가 제가 뽑아본 팔레트이고 네 번째가 원래 팔레트인데 이런 색상은 어떠신가요?
저는 지금 색상도 마음에 들기는 합니다!

**Comment by kimkanu** [comment]
@Sally-SH 300/500 밝기만 조절하면 제시해 주신 팔레트도 괜찮을 것 같습니다!

**Comment by julielee16** [comment]
@Sally-SH 저도 괜찮은것 같은데 저는 개인적으로 300만 올리면 괜찮다고 생각합니다!

**Comment by julielee16** [comment]
회의 후 보라색이 더 좋다 생각하여 

> 보라색은 적색맹/약의 경우에 positive한 색이랑 구분하기 힘들지만 보통 primary 액션이랑 positive한 액션은 의미에 차이가 크지 않으므로 겹쳐도 괜찮을 것 같기는 합니다.
> 
> ![Group 20(1)](https://user-images.githubusercontent.com/22598138/140634264-91d60061-0cf5-4e7f-a88e-77648a0ad4c3.png)

로 결정!

**Comment by kimkanu** [comment]
머지 하고 닫겠습니다!

**Comment by kimkanu** [comment]
#65
